// `README.md` — the orientation page for a generated system tree.
//
// The problem it solves (testability audit finding F12): `ddd generate system`
// wrote `api/`, `web_app/`, `e2e/`, `docker-compose.yml` and `.loom/` — and
// nothing that said what any of them were.  The emitted TEST projects were the
// sharpest edge: `e2e/` and `<frontend>/e2e/` are STANDALONE npm projects with
// their own `package.json`, so they need their own `npm install` and are not
// reached by a test run anywhere else in the tree.  The auditor found them by
// reading the file list and inferring.  `ddd new` scaffolds a README;
// `generate system` did not, and that asymmetry was the bug.
//
// Everything here is DERIVED from the model and from what the run actually
// emitted — nothing is a static blob.  A system with no frontend must not
// describe a frontend; a system that emitted no `e2e/` must not describe an
// e2e project; a `.loom/` without traceability must not claim it.  So the
// renderer runs LAST, over the finished output map, and asks that map what
// exists rather than predicting it.  The same rule covers the run recipes: a
// deployable's entrypoint is read from its OWN emitted manifest (a
// `package.json` script, a `.csproj`), and its environment from the same
// `composeService()` the compose file is rendered from, so neither can drift
// from what the generator really emits the way a hand-maintained
// per-platform table would.
//
// SCAFFOLD-ONCE (`src/util/scaffold-once.ts`).  The marker on the first line
// is load-bearing, for two reasons:
//
//   1. `ddd new` writes its OWN `README.md` at the project root and then tells
//      the author to run `ddd generate system main.ddd -o .` into that same
//      directory.  Without the marker, the first generate would silently
//      destroy the scaffold's README — following the scaffold's own advice.
//   2. A README is the file in a generated tree a human is MOST likely to
//      hand-edit.  Clobbering that on the next regen would be this module's
//      own small version of #2948.
//
// The marker buys the whole mechanic with no change to the CLI writer: it is
// detected in-band from the content, so the file already participates in
// `--dry-run` (listed as `keep (scaffold-once)` once it exists), in
// `.loomignore`, in `.loom/manifest.json`, and in the prune plan — exactly
// like every other emitted file.  It rides inside an HTML comment, which
// markdown renderers drop, so the rendered page is unaffected.

import type { DeployableIR, SystemIR } from "../ir/types/loom-ir.js";
import { platformFor } from "../platform/registry.js";
import { SCAFFOLD_ONCE_MARKER } from "../util/scaffold-once.js";

/** Everything the renderer needs that only the system orchestrator knows. */
export interface SystemReadmeContext {
  /** Compose service name / output subdirectory for a deployable name —
   *  `serviceSlug` in `src/system/index.ts`.  Passed in rather than
   *  re-implemented so the README can never disagree with the directory the
   *  run actually wrote. */
  slugOf(name: string): string;
  /** Output-relative path → content for everything this run emitted.  The
   *  renderer's only source of truth for what exists. */
  emitted: ReadonlyMap<string, string>;
  /** The Postgres image the emitted compose stack runs, so the host-side
   *  `docker run` the README hands the reader cannot drift from it. */
  dbImage: string;
}

/** The generated system's `README.md`. */
export function renderSystemReadme(sys: SystemIR, ctx: SystemReadmeContext): string {
  const out: string[] = [];
  // First line, and it must stay first: `isScaffoldOnce` scans only line one.
  out.push(
    `<!-- Generated by Loom. ${SCAFFOLD_ONCE_MARKER}: edit freely — regeneration will not overwrite this file. -->`,
  );
  out.push(`# ${sys.name}`);
  out.push("");
  out.push(
    "Generated by `ddd generate system` from a `.ddd` model. The model is the source of truth; everything here is build output.",
  );
  out.push("");
  out.push(...whatIsHere(sys, ctx));
  out.push(...runIt(sys, ctx));
  out.push(...tests(sys, ctx));
  out.push(...loomDir(ctx));
  out.push(...regenerating());
  return `${out
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

// ---------------------------------------------------------------------------
// What is here
// ---------------------------------------------------------------------------

function whatIsHere(sys: SystemIR, ctx: SystemReadmeContext): string[] {
  const lines = ["## What is here", ""];
  lines.push("| Directory | Platform | Port | Serves |");
  lines.push("| --- | --- | --- | --- |");
  for (const d of sys.deployables) {
    lines.push(`| \`${ctx.slugOf(d.name)}/\` | ${d.platform} | ${d.port} | ${serves(d, ctx)} |`);
  }
  lines.push("");
  const db = sys.deployables.some((d) => platformFor(d.platform).needsDb)
    ? " with a Postgres (`db-init/` creates one database per backend)"
    : "";
  lines.push(
    sys.deployables.length === 1
      ? `\`docker-compose.yml\` runs it${db}.`
      : `\`docker-compose.yml\` wires those together${db}.`,
  );
  lines.push("");
  return lines;
}

/** One phrase for what a deployable is for, from the model. */
function serves(d: DeployableIR, ctx: SystemReadmeContext): string {
  if (platformFor(d.platform).isFrontend) {
    const ui = d.uiName ? `\`${d.uiName}\` UI` : "UI";
    return d.targetName ? `${ui}, calling \`${ctx.slugOf(d.targetName)}\`` : ui;
  }
  const contexts = d.contextNames.map((c) => `\`${c}\``).join(", ");
  const api = contexts ? `HTTP API for ${contexts}` : "HTTP API";
  return d.uiName ? `${api}, and the \`${d.uiName}\` UI` : api;
}

// ---------------------------------------------------------------------------
// Run it
// ---------------------------------------------------------------------------

function runIt(sys: SystemIR, ctx: SystemReadmeContext): string[] {
  const lines = ["## Run it", "", "The whole stack, including its database:", "", "```bash"];
  lines.push("docker compose up --build");
  lines.push("```");
  lines.push("");
  for (const d of sys.deployables) {
    lines.push(`- \`${ctx.slugOf(d.name)}\` — <http://localhost:${d.port}>`);
  }
  lines.push("");
  const recipes = sys.deployables
    .map((d) => ({ d, steps: layoutFor(d, ctx).run?.(localEnv(d, sys, ctx), d) }))
    .filter((r): r is { d: DeployableIR; steps: string[] } => r.steps !== undefined);
  if (recipes.length > 0) {
    lines.push("### Or one deployable at a time");
    lines.push("");
    lines.push(
      "Each deployable is an ordinary project and runs on its own, without compose. Each recipe below binds it to the port the model gives it above — which is also where the tests look for it.",
    );
    lines.push("");
    for (const { d, steps } of recipes) {
      lines.push(`\`${ctx.slugOf(d.name)}/\` — ${d.platform}:`);
      lines.push("");
      lines.push("```bash");
      lines.push(`cd ${ctx.slugOf(d.name)}`);
      lines.push(...steps);
      lines.push("```");
      lines.push("");
    }
    if (sys.deployables.some((d) => platformFor(d.platform).needsDb)) {
      // NOT `docker compose up -d db`: the compose `db` service publishes no
      // port (nothing outside the compose network is meant to reach it), so
      // that command leaves `localhost:5432` refused and the recipes above
      // failing. This starts the same image with the port published and the
      // emitted `db-init/` mounted, so each backend's database exists.
      lines.push(
        "A backend started this way still needs its Postgres, and the compose `db` service does not publish a port. Start one that does — same image, with the emitted `db-init/` mounted so each backend's database is created:",
      );
      lines.push("");
      lines.push("```bash");
      lines.push("docker run --rm -d --name loom-db -p 5432:5432 \\");
      lines.push("  -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres \\");
      lines.push('  -v "$PWD/db-init:/docker-entrypoint-initdb.d:ro" \\');
      lines.push(`  ${ctx.dbImage}`);
      lines.push("```");
      lines.push("");
    }
  }
  return lines;
}

/**
 * The deployable's compose environment, rewritten for a run on the host.
 *
 * Only the variables the rewrite CHANGES are kept: those are exactly the ones
 * whose value names a compose service (`db`, or a sibling deployable), and so
 * exactly the ones that are wrong outside compose. Everything else already
 * has the right default compiled in, and listing it would bury the two lines
 * that matter.
 */
function localEnv(
  d: DeployableIR,
  sys: SystemIR,
  ctx: SystemReadmeContext,
): Record<string, string> {
  const shape = platformFor(d.platform).composeService({
    deployable: d,
    sys,
    slug: ctx.slugOf(d.name),
  });
  // Every compose hostname this system can mention, mapped to its host
  // address: the database, plus each deployable at the port it publishes.
  //
  // Two spellings, because the backends do not agree on one.  Four of the five
  // put the database in a URL authority (`…@db:5432/x`, `jdbc:postgresql://db:5432/x`);
  // .NET uses ADO.NET keywords (`Host=db;Port=5432;…`), where the host and the
  // port are separate fields and a `db:5432` match never fires.  Missing the
  // second spelling silently dropped `ConnectionStrings__Default` from every
  // dotnet recipe — the one variable that deployable cannot boot without.
  const hosts: Array<[string, string]> = [
    ["db:5432", "localhost:5432"],
    ["Host=db;", "Host=localhost;"],
  ];
  for (const peer of sys.deployables) {
    const peerSlug = ctx.slugOf(peer.name);
    const internal = platformFor(peer.platform).composeService({
      deployable: peer,
      sys,
      slug: peerSlug,
    }).internalPort;
    hosts.push([`${peerSlug}:${internal}`, `localhost:${peer.port}`]);
  }
  const local: Record<string, string> = {};
  for (const [k, v] of shape.env) {
    let rewritten = v;
    for (const [from, to] of hosts) rewritten = rewritten.split(from).join(to);
    if (rewritten !== v) local[k] = rewritten;
  }
  return local;
}

/** `K=v K2=v2 ` for a command prefix, or `""`. */
function envPrefix(env: Record<string, string>): string {
  const parts = Object.entries(env).map(([k, v]) => `${k}=${shellQuote(v)}`);
  return parts.length > 0 ? `${parts.join(" ")} ` : "";
}

function shellQuote(v: string): string {
  return /^[A-Za-z0-9_./:@%+=-]+$/.test(v) ? v : `'${v.split("'").join(`'\\''`)}'`;
}

// ---------------------------------------------------------------------------
// Project layouts — how a deployable boots and how its unit tests run
// ---------------------------------------------------------------------------

/** What a deployable's emitted project supports, derived from the files it
 *  actually emitted.  Both members are optional: an unrecognised layout
 *  contributes no recipe rather than a guessed one, and the compose recipe
 *  plus `<slug>/Dockerfile` still cover it. */
interface ProjectLayout {
  /** Shell steps that start the deployable on the host, after `cd <slug>`. */
  run?: (env: Record<string, string>, d: DeployableIR) => string[];
  /** The one command that runs the project's emitted unit tests. */
  test?: string;
  /** True for an emitted path (relative to the deployable dir) that is one of
   *  those unit tests — so a project with no emitted tests says nothing. */
  isTestFile: (rel: string) => boolean;
}

function layoutFor(d: DeployableIR, ctx: SystemReadmeContext): ProjectLayout {
  const slug = ctx.slugOf(d.name);
  const pkg = ctx.emitted.get(`${slug}/package.json`);
  if (pkg !== undefined) {
    const scripts = packageScripts(pkg);
    return {
      // A vite frontend serves its BUILT bundle from `preview`; the emitted
      // script pins the container port, so override it to the model's port —
      // outside compose there is no port mapping to do that for us, and two
      // deployables would otherwise both land on the container default.
      run: scripts.preview
        ? (env, dep) => [
            "npm install",
            ...(scripts.build ? ["npm run build"] : []),
            `${envPrefix(env)}npm run preview -- --port ${dep.port}`,
          ]
        : scripts.dev
          ? (env, dep) => [
              "npm install",
              `${envPrefix({ ...env, PORT: String(dep.port) })}npm run dev`,
            ]
          : undefined,
      test: scripts.test ? "npm test" : undefined,
      isTestFile: (rel) => rel.endsWith(".test.ts") || rel.endsWith(".test.tsx"),
    };
  }
  if (hasEmitted(ctx, slug, (p) => p.endsWith(".csproj"))) {
    return {
      run: (env, dep) => [
        `${envPrefix({ ...env, ASPNETCORE_URLS: `http://localhost:${dep.port}` })}dotnet run`,
      ],
      test: "dotnet test",
      isTestFile: (rel) => rel.endsWith("Tests.cs") || rel.startsWith("Tests/"),
    };
  }
  if (hasEmitted(ctx, slug, (p) => p === "pom.xml")) {
    return {
      run: (env, dep) => [
        `${envPrefix({ ...env, SERVER_PORT: String(dep.port) })}./mvnw spring-boot:run`,
      ],
      test: "./mvnw test",
      isTestFile: (rel) => rel.endsWith("Test.java") || rel.endsWith("Tests.java"),
    };
  }
  if (hasEmitted(ctx, slug, (p) => p === "mix.exs")) {
    return {
      run: (env, dep) => [
        "mix deps.get",
        `${envPrefix({ ...env, PORT: String(dep.port) })}mix phx.server`,
      ],
      test: "mix test",
      isTestFile: (rel) => rel.endsWith("_test.exs"),
    };
  }
  if (hasEmitted(ctx, slug, (p) => p === "requirements.txt" || p === "pyproject.toml")) {
    return {
      run: (env, dep) => [
        "pip install -r requirements.txt",
        `${envPrefix(env)}uvicorn app.main:app --port ${dep.port}`,
      ],
      test: "pytest",
      isTestFile: (rel) => /(^|\/)test_[^/]+\.py$/.test(rel),
    };
  }
  return { isTestFile: () => false };
}

function hasEmitted(
  ctx: SystemReadmeContext,
  slug: string,
  match: (rel: string) => boolean,
): boolean {
  const prefix = `${slug}/`;
  for (const path of ctx.emitted.keys()) {
    if (path.startsWith(prefix) && match(path.slice(prefix.length))) return true;
  }
  return false;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/** Small counts read better as words in prose; anything larger stays a numeral. */
function spellSmall(n: number): string {
  return ["zero", "one", "two", "three", "four", "five", "six"][n] ?? String(n);
}

function packageScripts(raw: string): Record<string, string> {
  try {
    const parsed: unknown = JSON.parse(raw);
    const scripts =
      parsed && typeof parsed === "object" ? (parsed as { scripts?: unknown }).scripts : undefined;
    return scripts && typeof scripts === "object" ? (scripts as Record<string, string>) : {};
  } catch {
    return {};
  }
}

// ---------------------------------------------------------------------------
// The test projects — the reason this file exists
// ---------------------------------------------------------------------------

function tests(sys: SystemIR, ctx: SystemReadmeContext): string[] {
  // Backends whose project both knows how to run tests AND emitted some.
  const unit = sys.deployables
    .map((d) => ({ slug: ctx.slugOf(d.name), layout: layoutFor(d, ctx) }))
    .filter(
      (u): u is { slug: string; layout: ProjectLayout & { test: string } } =>
        u.layout.test !== undefined && hasEmitted(ctx, u.slug, u.layout.isTestFile),
    );
  // A standalone project is one with its OWN package.json — that is precisely
  // what makes it invisible to a test run elsewhere in the tree, and what
  // makes its own `npm install` mandatory.
  const hasRootE2E = ctx.emitted.has("e2e/package.json");
  const uiE2E = sys.deployables
    .map((d) => ctx.slugOf(d.name))
    .filter((slug) => ctx.emitted.has(`${slug}/e2e/package.json`));

  const lines = ["## Tests", ""];
  const inventory: string[] = [];
  for (const u of unit) inventory.push(`\`${u.slug}/\` — unit tests, in-process`);
  if (hasRootE2E) inventory.push("`e2e/` — API tests over HTTP, **its own npm project**");
  for (const slug of uiE2E) {
    inventory.push(`\`${slug}/e2e/\` — browser tests, **its own npm project**`);
  }
  if (inventory.length === 0) {
    lines.push("This model declares no tests, so none were emitted.");
    lines.push("");
    return lines;
  }
  lines.push(
    inventory.length === 1
      ? "One project in this tree carries tests:"
      : `${capitalize(spellSmall(inventory.length))} separate projects in this tree carry tests, each run on its own:`,
  );
  lines.push("");
  for (const item of inventory) lines.push(`- ${item}`);
  lines.push("");
  if (hasRootE2E || uiE2E.length > 0) {
    lines.push(
      "The `e2e` projects have their own `package.json` and their own dependencies. Nothing else in this tree installs or runs them — each needs its own `npm install`, and each talks to a **running** stack, so start one first.",
    );
    lines.push("");
  }
  // One heading and one explanation for ALL the unit suites, then a block per
  // backend. Repeating the same paragraph under a `###` per deployable read
  // as boilerplate at three backends and buried the commands.
  if (unit.length > 0) {
    lines.push(unit.length === 1 ? `### \`${unit[0].slug}/\` — unit tests` : "### Unit tests");
    lines.push("");
    lines.push(
      "Emitted from the model's `test` blocks: the domain rules, exercised in process. No database, no running server.",
    );
    lines.push("");
  }
  for (const u of unit) {
    lines.push("```bash");
    lines.push(`cd ${u.slug}`);
    if (u.layout.test === "npm test") lines.push("npm install");
    lines.push(u.layout.test);
    lines.push("```");
    lines.push("");
  }
  if (hasRootE2E) lines.push(...rootE2E(sys, ctx));
  for (const slug of uiE2E) lines.push(...uiE2ESection(slug, hasRootE2E));
  return lines;
}

function rootE2E(sys: SystemIR, ctx: SystemReadmeContext): string[] {
  const lines = ["### `e2e/` — API tests over HTTP", ""];
  lines.push(
    "A standalone [vitest](https://vitest.dev) project, emitted from the model's `test e2e` blocks. It drives the running stack over HTTP.",
  );
  lines.push("");
  lines.push("```bash");
  lines.push("cd e2e");
  lines.push("npm install");
  lines.push("npm test");
  lines.push("```");
  lines.push("");
  lines.push(
    "Each deployable's base URL comes from an environment variable, defaulting to its port above. Override them to point the suite at a stack that is not on `localhost`:",
  );
  lines.push("");
  lines.push("```bash");
  // Every assignment gets its own continued line, including the last one, so
  // the block is correct at one deployable as well as at four.
  for (const d of sys.deployables) {
    lines.push(`E2E_${ctx.slugOf(d.name).toUpperCase()}_BASE=http://localhost:${d.port} \\`);
  }
  lines.push("  npm test");
  lines.push("```");
  lines.push("");
  lines.push(...freshDatabase());
  return lines;
}

/**
 * The state contract for the emitted e2e suite.
 *
 * Finding F3: the emitted project has no reset hooks of any kind, so it is
 * green on an empty database and can be red on a second run against the same
 * one. Documenting that plainly is the honest fallback D-1 settled on. If a
 * generated reset seam lands, THIS is the paragraph that has to change with
 * it — a README that describes isolation the suite does not have would be
 * worse than the silence it replaced.
 */
function freshDatabase(): string[] {
  return [
    "#### It expects a fresh database",
    "",
    "The emitted tests create rows and never delete them — there are no reset hooks in this project. They pass against an empty database; a second run against the same one can fail, because a test that creates a uniquely-keyed row now collides with the row its previous run left behind, and a test that lists or counts results sees those leftovers too.",
    "",
    "So reset the database between runs — and **restart the backends with it**. Each backend applies its migrations once, at boot, so a database recreated under a running process has no tables at all and every test fails on the missing schema rather than on leftovers.",
    "",
    "Under compose, one command does both:",
    "",
    "```bash",
    "docker compose down -v && docker compose up --build -d",
    "```",
    "",
    "Running natively, recreate the database container and restart each backend against it.",
    "",
  ];
}

function uiE2ESection(slug: string, sharesDbWithRootE2E: boolean): string[] {
  const lines = [`### \`${slug}/e2e/\` — browser tests`, ""];
  lines.push(
    `A standalone [Playwright](https://playwright.dev) project: a generated smoke spec plus the page objects it drives, and a spec per \`test e2e ui\` block in the model. It needs a browser binary as well as its npm dependencies, and a running stack to open.`,
  );
  lines.push("");
  lines.push("```bash");
  lines.push(`cd ${slug}/e2e`);
  lines.push("npm install");
  lines.push("npx playwright install chromium");
  lines.push("npx playwright test");
  lines.push("```");
  lines.push("");
  lines.push(
    `\`E2E_BASE_URL\` sets the front end it opens, defaulting to \`${slug}\`'s port above.${
      sharesDbWithRootE2E
        ? " It writes through the UI to the same database as `e2e/`, so the fresh-database note above applies to it too."
        : ""
    }`,
  );
  lines.push("");
  return lines;
}

// ---------------------------------------------------------------------------
// .loom/ and regeneration
// ---------------------------------------------------------------------------

function loomDir(ctx: SystemReadmeContext): string[] {
  const has = (p: string) => ctx.emitted.has(p);
  const parts: string[] = [];
  if (has(".loom/traceability.md")) parts.push("requirement traceability");
  if (has(".loom/coverage.md") || has(".loom/gaps.md")) parts.push("coverage and gaps reports");
  if (has(".loom/wire-spec.json")) parts.push("the wire spec every API speaks");
  if (has(".loom/domain.mmd")) parts.push("Mermaid diagrams");
  if (has(".loom/architecture.c4")) parts.push("a LikeC4 architecture model");
  const list = parts.length > 0 ? parts.join(", ") : "derived views of the model";
  return [
    "## `.loom/`",
    "",
    `Derived artifacts — ${list}. Every one is regenerated from the model on each run, so edits there are lost: read them, don't edit them.`,
    "",
  ];
}

function regenerating(): string[] {
  return [
    "## Regenerating",
    "",
    "This tree is output. Change the `.ddd` model and re-run the same `ddd generate system … -o .` over it: files whose content changed are rewritten, files the model no longer produces are deleted, and files it never wrote are left alone.",
    "",
    "**It will overwrite a file you hand-edited.** To keep an edit, pin the file in `.loomignore` — gitignore syntax, paths relative to this directory — and generation skips it from then on. `ddd generate system --dry-run` prints the whole write/skip/delete plan first, without touching anything.",
    "",
    "This README is the one exception: it is written once and then left alone, so it is yours to edit. The flip side is that it will not pick up later changes to the model — delete it and regenerate to get a current one.",
    "",
  ];
}
