import { describe, expect, it } from "vitest";

import { emitJavaMigrations } from "../../../src/generator/java/emit/migrations.js";
import { renderPgStep } from "../../../src/generator/sql-pg.js";
import type { MigrationsIR, SchemaSnapshot } from "../../../src/ir/types/migrations-ir.js";
import { generateSystemFiles } from "../../_helpers/index.js";

// ---------------------------------------------------------------------------
// Java migrations emitter — MigrationsIR → Flyway versioned SQL under
// `src/main/resources/db/migration/` (M-T9.20: the one backend whose
// migrations emitter had no dedicated test; node/.NET/python/elixir each have
// one).  The behaviour that matters is the FILE NAME, because Flyway — not
// Loom — parses it: a name Flyway cannot parse is silently not a migration,
// and two files with the same version abort the whole migrate at boot.  So
// the names are checked against Flyway's own versioned-migration grammar
// (`V<version>__<description>.sql`, version = dot/underscore-separated digit
// groups, description after the FIRST `__`), not against a string this test
// or the emitter makes up — rule 12 of the completion plan.  The booted half
// (Flyway applying them on Postgres) is `test/e2e/migration-evolution-java`.
// ---------------------------------------------------------------------------

/** Flyway's versioned-migration file-name grammar (default prefix `V`,
 *  separator `__`, suffix `.sql`). */
const FLYWAY_VERSIONED = /^V(\d+(?:[._]\d+)*)__([^/]+)\.sql$/;

const SNAP: SchemaSnapshot = { schemaVersion: 1, lastVersion: "20260101000000", tables: [] };

const CREATE_ORDERS: MigrationsIR["steps"][number] = {
  op: "createTable",
  table: {
    name: "orders",
    ownerModule: "Sales",
    columns: [{ name: "id", type: { kind: "uuid" }, nullable: false }],
    primaryKey: ["id"],
    foreignKeys: [],
    indexes: [],
  },
};

function ir(
  module: string,
  steps: MigrationsIR["steps"],
  opts: { version?: string; name?: string } = {},
): MigrationsIR {
  return {
    module,
    storageName: "",
    baseline: SNAP,
    next: SNAP,
    steps,
    version: opts.version ?? "20260101000000",
    name: opts.name ?? "Initial",
  };
}

function emit(migrations: MigrationsIR[]): Map<string, string> {
  const out = new Map<string, string>();
  emitJavaMigrations(migrations, out);
  return out;
}

const fileName = (p: string): string => p.slice(p.lastIndexOf("/") + 1);

describe("java migrations emitter (Flyway)", () => {
  it("emits one versioned SQL file per non-empty MigrationsIR under db/migration/", () => {
    const out = emit([ir("Sales", [CREATE_ORDERS])]);
    expect([...out.keys()]).toEqual([
      "src/main/resources/db/migration/V20260101000000.1__Sales_Initial.sql",
    ]);
    const sql = out.values().next().value!;
    // The body is the SHARED Postgres renderer's output, verbatim — Java never
    // re-derives schema.
    expect(sql).toContain(renderPgStep(CREATE_ORDERS));
    expect(sql.startsWith("-- Auto-generated by Loom for module Sales")).toBe(true);
  });

  it("every emitted name parses under Flyway's versioned grammar, description intact", () => {
    const out = emit([
      ir("Sales", [CREATE_ORDERS], { name: "Initial" }),
      ir("Billing", [CREATE_ORDERS], { name: "Add_Invoice Totals!" }),
    ]);
    for (const p of out.keys()) {
      const m = FLYWAY_VERSIONED.exec(fileName(p));
      expect(m, `${p} is not a Flyway versioned migration name`).not.toBeNull();
      // The description may not contain a second `__`, or Flyway would split
      // the version at the wrong separator.
      expect(m![2]!.includes("__"), p).toBe(false);
    }
    // Non-word characters are stripped from module + name (`_`, space, `!`).
    expect([...out.keys()].map(fileName)).toContain(
      "V20260101000000.2__Billing_AddInvoiceTotals.sql",
    );
  });

  it("modules sharing one snapshot timestamp still get DISTINCT Flyway versions", () => {
    // Several modules share the canonical base timestamp on a fresh project;
    // Flyway aborts `migrate` on a duplicate version, so the per-module index
    // is what keeps them apart.
    const out = emit([
      ir("Sales", [CREATE_ORDERS]),
      ir("Billing", [CREATE_ORDERS]),
      ir("Shipping", [CREATE_ORDERS]),
    ]);
    const versions = [...out.keys()].map((p) => FLYWAY_VERSIONED.exec(fileName(p))![1]!);
    expect(versions).toHaveLength(3);
    expect(new Set(versions).size).toBe(3);
  });

  it("skips an EMPTY migration without renumbering the rest", () => {
    // The index is the module's position in the deployable, not a counter of
    // emitted files — so a module whose migration is empty this round keeps
    // the next module's version stable across rounds.
    const out = emit([ir("Sales", []), ir("Billing", [CREATE_ORDERS])]);
    expect([...out.keys()].map(fileName)).toEqual(["V20260101000000.2__Billing_Initial.sql"]);
  });

  it("a java deployable's generated tree carries a Flyway migration creating its aggregate table", async () => {
    const files = await generateSystemFiles(`
      system S {
        subdomain Sales {
          context Orders {
            aggregate Order with crudish { code: string }
            repository OrderRepo for Order { }
          }
        }
        api OrdersApi from Sales
        storage db { type: postgres }
        resource st { for: Orders, kind: state, use: db }
        deployable api { platform: java contexts: [Orders] dataSources: [st] serves: OrdersApi port: 8080 }
      }`);
    const migrations = [...files].filter(([p]) => p.includes("/src/main/resources/db/migration/"));
    expect(
      migrations.length,
      "no Flyway migration emitted for the java deployable",
    ).toBeGreaterThan(0);
    for (const [p] of migrations) expect(fileName(p)).toMatch(FLYWAY_VERSIONED);
    expect(migrations.map(([, sql]) => sql).join("\n")).toMatch(/CREATE TABLE[^(]*"?orders"?/);
  });
});
