// ---------------------------------------------------------------------------
// The per-target reserved-identifier contract — ONE table, ONE escaping path.
//
// A `.ddd` name is Loom-legal and may still be fatal in a target: `def` /
// `lambda` in python (#3102), `base` / `event` in C#, `end` / `do` in elixir,
// `member` in F#, `break` / `eval` as a TS parameter, `then` as a TS method
// (it makes every aggregate a thenable).  Every backend used to carry its own
// keyword set beside its own escape helper — five in `naming.ts`, a drifted
// Java copy in `java/naming.ts` (it had `record`/`yield`/`sealed`/`permits`,
// `naming.ts` did not), F#'s in `feliz/fs-ident.ts`, none for Dart — so a word
// one table knew and another did not was escaped on one backend and fatal on
// the next.  They are now views of {@link RESERVED}; every `escape<Lang>Ident`
// delegates to {@link escapeTargetIdent}.
//
// Ruling D-TARGET-RESERVED-NAMES (docs/decisions.md): escape per backend,
// never refuse.  The escape is visible only in generated HOST source; the wire
// key, the OpenAPI schema and the stored column keep the declared name.
//
// The gate is `test/fixtures/corpus/target-reserved-words.ddd`, which names a
// field, an enum value, an operation and its parameter after every entry here
// that the `.ddd` grammar admits, on every backend's compile leg;
// `test/util/target-identifiers.test.ts` fails when a table entry the grammar
// admits is missing from that fixture, and checks the tables that have an
// authoritative source runnable in CI against it (python's `keyword` module,
// the TypeScript scanner).
// ---------------------------------------------------------------------------

/** Every target whose identifiers Loom spells from user names. */
export const IDENT_TARGETS = [
  "ts",
  "csharp",
  "java",
  "python",
  "elixir",
  "fsharp",
  "dart",
] as const;
export type IdentTarget = (typeof IDENT_TARGETS)[number];

/** Words that cannot be spelled as a bare BINDING (local, parameter, field,
 *  method) in each target. */
const RESERVED: Record<IdentTarget, ReadonlySet<string>> = {
  /** TS / JS: the strict-mode + module reserved words, plus `arguments` and
   *  `eval`, which strict mode (every ES module and every class body) refuses
   *  as a binding name (TS1100 / TS1210). */
  ts: new Set([
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "new",
    "null",
    "return",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
    "let",
    "static",
    "implements",
    "interface",
    "package",
    "private",
    "protected",
    "public",
    "await",
    "arguments",
    "eval",
  ]),
  /** C#: the reserved keywords, plus `await` — contextual, but every generated
   *  handler is an `async` method, where it cannot be an identifier (CS4003).
   *  The other contextual keywords are legal identifiers. */
  csharp: new Set([
    "await",
    "abstract",
    "as",
    "base",
    "bool",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "checked",
    "class",
    "const",
    "continue",
    "decimal",
    "default",
    "delegate",
    "do",
    "double",
    "else",
    "enum",
    "event",
    "explicit",
    "extern",
    "false",
    "finally",
    "fixed",
    "float",
    "for",
    "foreach",
    "goto",
    "if",
    "implicit",
    "in",
    "int",
    "interface",
    "internal",
    "is",
    "lock",
    "long",
    "namespace",
    "new",
    "null",
    "object",
    "operator",
    "out",
    "override",
    "params",
    "private",
    "protected",
    "public",
    "readonly",
    "ref",
    "return",
    "sbyte",
    "sealed",
    "short",
    "sizeof",
    "stackalloc",
    "static",
    "string",
    "struct",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "uint",
    "ulong",
    "unchecked",
    "unsafe",
    "ushort",
    "using",
    "virtual",
    "void",
    "volatile",
    "while",
  ]),
  /** Java: reserved words and literals, plus the restricted identifiers
   *  (`var`, `record`, `yield`, `sealed`, `permits`) that cannot name a type
   *  or a package segment. */
  java: new Set([
    "abstract",
    "assert",
    "boolean",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extends",
    "final",
    "finally",
    "float",
    "for",
    "goto",
    "if",
    "implements",
    "import",
    "instanceof",
    "int",
    "interface",
    "long",
    "native",
    "new",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "short",
    "static",
    "strictfp",
    "super",
    "switch",
    "synchronized",
    "this",
    "throw",
    "throws",
    "transient",
    "try",
    "void",
    "volatile",
    "while",
    "var",
    "true",
    "false",
    "null",
    "record",
    "yield",
    "sealed",
    "permits",
  ]),
  /** Python: `keyword.kwlist`, the soft keywords `match` / `case`, the method
   *  receivers `self` / `cls` (every generated method binds one, so a member of
   *  that name is a duplicate parameter), and the builtin / `BaseModel` names a
   *  generated class body would shadow. */
  python: new Set([
    "self",
    "cls",
    // Builtin type names every generated module annotates with: a pydantic /
    // dataclass body is ONE scope, so a field `str: str` rebinds `str` and every
    // later `x: str` annotation names the field (mypy: "Variable … is not valid
    // as a type").
    "str",
    "int",
    "float",
    "bool",
    "bytes",
    "dict",
    "list",
    // `BaseModel` methods a field of that name would override with a non-method
    // (mypy: incompatible override of "def dict(self, …)").
    "json",
    "copy",
    "False",
    "None",
    "True",
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
    "match",
    "case",
  ]),
  /** Elixir: reserved words plus the special forms / Kernel macros that are
   *  unsafe as a plain variable binding. */
  elixir: new Set([
    "true",
    "false",
    "nil",
    "when",
    "and",
    "or",
    "not",
    "in",
    "fn",
    "do",
    "end",
    "catch",
    "rescue",
    "after",
    "else",
    "def",
    "defp",
    "defmodule",
    "if",
    "unless",
    "case",
    "cond",
    "with",
    "for",
    "receive",
    "try",
    "raise",
    "import",
    "alias",
    "require",
    "use",
    "quote",
    "unquote",
  ]),
  /** F#: the reserved-keyword set (F# 4.1+ spec §3.4) including the words
   *  reserved for future use, which the compiler rejects too. */
  fsharp: new Set([
    "abstract",
    "and",
    "as",
    "assert",
    "base",
    "begin",
    "class",
    "default",
    "delegate",
    "do",
    "done",
    "downcast",
    "downto",
    "elif",
    "else",
    "end",
    "exception",
    "extern",
    "false",
    "finally",
    "fixed",
    "for",
    "fun",
    "function",
    "global",
    "if",
    "in",
    "inherit",
    "inline",
    "interface",
    "internal",
    "lazy",
    "let",
    "match",
    "member",
    "module",
    "mutable",
    "namespace",
    "new",
    "not",
    "null",
    "of",
    "open",
    "or",
    "override",
    "private",
    "public",
    "rec",
    "return",
    "select",
    "static",
    "struct",
    "then",
    "to",
    "true",
    "try",
    "type",
    "upcast",
    "use",
    "val",
    "void",
    "when",
    "while",
    "with",
    "yield",
    "atomic",
    "break",
    "checked",
    "component",
    "const",
    "constraint",
    "constructor",
    "continue",
    "eager",
    "event",
    "external",
    "functor",
    "include",
    "method",
    "mixin",
    "object",
    "parallel",
    "process",
    "protected",
    "pure",
    "sealed",
    "tailcall",
    "trait",
    "virtual",
    "volatile",
  ]),
  /** Dart: the reserved words (never an identifier) plus `await` / `yield`,
   *  which are reserved inside the async / generator bodies Flutter code
   *  is made of.  (Built-in identifiers such as `dynamic` are legal names.) */
  dart: new Set([
    "assert",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "else",
    "enum",
    "extends",
    "false",
    "final",
    "finally",
    "for",
    "if",
    "in",
    "is",
    "new",
    "null",
    "rethrow",
    "return",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "var",
    "void",
    "while",
    "with",
    "await",
    "yield",
  ]),
};

/** How each target spells a reserved word as an identifier: C#'s verbatim
 *  `@base`, F#'s double-backtick ``member``, a trailing underscore
 *  everywhere else (`def_`, `end_`, `break_`). */
const ESCAPE: Record<IdentTarget, (name: string) => string> = {
  ts: (n) => `${n}_`,
  csharp: (n) => `@${n}`,
  java: (n) => `${n}_`,
  python: (n) => `${n}_`,
  elixir: (n) => `${n}_`,
  fsharp: (n) => `\`\`${n}\`\``,
  dart: (n) => `${n}_`,
};

/** True when `name` cannot be spelled as a bare identifier in `target`. */
export function isReserved(target: IdentTarget, name: string): boolean {
  return RESERVED[target].has(name);
}

/** THE escaping path: `name`, spelled so `target` accepts it as an
 *  identifier.  A non-reserved name passes through byte-identically. */
export function escapeTargetIdent(target: IdentTarget, name: string): string {
  return RESERVED[target].has(name) ? ESCAPE[target](name) : name;
}

/** The reserved words of `target`, sorted — for the census and docs. */
export function reservedWords(target: IdentTarget): readonly string[] {
  return [...RESERVED[target]].sort();
}

/** Names a target reserves as a CLASS MEMBER although they are legal
 *  bindings.  TS: a method named `constructor` IS the constructor, and a
 *  method named `then` makes every instance a thenable, so `await
 *  repo.getById(...)` resolves to whatever `then` does (TS1320).  Escaped
 *  with a trailing underscore at the member declaration and every call. */
const RESERVED_MEMBERS: Partial<Record<IdentTarget, ReadonlySet<string>>> = {
  ts: new Set(["constructor", "then"]),
};

/** `name` as a class-member name in `target`. */
export function escapeTargetMember(target: IdentTarget, name: string): string {
  return RESERVED_MEMBERS[target]?.has(name) ? `${name}_` : name;
}
