// Extern frontend functions — the logic escape hatch
// (extern-function-hook-escape-hatch.md §3).  For each
// `function <name>(params): T extern from "<path>"` ui member, Loom owns
// two files and imports the user's module:
//
//   ① `src/lib/extern/<name>.signature.ts` — the typed signature
//      (`export type <Name>Fn = (params) => T;`), wire-DTO-typed so a
//      domain change regenerates the type and breaks a stale impl.
//   ② `src/lib/<name>.ts` — the conformance shim: a stable import for
//      call sites AND the contract enforcement point
//      (`export const <name>: <Name>Fn = _impl;`).  A missing module
//      fails the shim's import; a mismatched signature fails the
//      `const` annotation — `tsc` is the fail-fast, both ways.
//
// The user owns the module at the `from` path; Loom never writes it.
//
// Shared by the react and svelte frontends — the only frontend-shaped
// difference is where the wire-DTO api modules live (react `src/api/`,
// SvelteKit `src/lib/api/`), threaded as `apiImportRoot`.

import { diagMessage } from "../../diagnostics/messages.js";
import type { TypeIR, UiFunctionIR } from "../../ir/types/loom-ir.js";
import { lowerFirst, upperFirst } from "../../util/naming.js";

/** INTERNAL FLOOR for a signature type with no TS spelling — the twin of
 *  `component-prop-type.ts`'s `propTypeFloor`, refused at phase ⑦ by the same
 *  `loom.frontend-prop-type-unsupported` gate.  Measured before that gate
 *  existed: `function fmt(m: money): string extern from "./fmt"` validated
 *  `0 error(s), 0 warning(s)` and then died here with a raw stack trace. */
function signatureFloor(what: string): Error {
  return new Error(diagMessage("loom.frontend-prop-type-unsupported#emit-invariant", { what }));
}

/** Map a Loom type to its wire-side TS spelling for the signature.
 *  Aggregates use the wire DTO (`<Agg>Response`, recorded into
 *  `dtoImports` for the import block); primitives map to their TS
 *  equivalents.  Unsupported shapes fail loud — emitting `any` would
 *  silently void the contract the hatch exists to enforce. */
function wireTsType(t: TypeIR, dtoImports: Map<string, string>, apiImportRoot: string): string {
  switch (t.kind) {
    case "primitive":
      switch (t.name) {
        case "int":
        case "long":
        case "decimal":
          return "number";
        case "bool":
          return "boolean";
        case "string":
        case "datetime":
        case "guid":
          return "string";
        case "json":
          return "unknown";
        default:
          throw signatureFloor(`primitive '${t.name}'`);
      }
    case "entity":
      dtoImports.set(`${t.name}Response`, `${apiImportRoot}/${lowerFirst(t.name)}`);
      return `${t.name}Response`;
    case "id":
      return "string";
    case "enum":
      return "string";
    case "array":
      return `${wireTsType(t.element, dtoImports, apiImportRoot)}[]`;
    case "optional":
      return `${wireTsType(t.inner, dtoImports, apiImportRoot)} | undefined`;
    default:
      throw signatureFloor(`type kind '${t.kind}'`);
  }
}

/** ① The machine-owned typed signature at
 *  `src/lib/extern/<name>.signature.ts`. */
export function buildExternFunctionSignature(
  fn: UiFunctionIR,
  /** Where the wire-DTO api modules live, as seen from
   *  `src/lib/extern/` — react `"../../api"`, SvelteKit `"../api"`. */
  apiImportRoot = "../../api",
): string {
  const dtoImports = new Map<string, string>();
  const params = fn.params
    .map((p) => `${p.name}: ${wireTsType(p.type, dtoImports, apiImportRoot)}`)
    .join(", ");
  const ret = wireTsType(fn.returnType, dtoImports, apiImportRoot);
  const importLines = [...dtoImports.entries()]
    .map(([type, mod]) => `import type { ${type} } from "${mod}";\n`)
    .join("");
  return `// AUTO-GENERATED by Loom — typed signature for extern function '${fn.name}'.
// Do not edit; overwritten on every generate.  Annotate your hand-written
// implementation with this type to get body-level contract checking.
${importLines}export type ${upperFirst(fn.name)}Fn = (${params}) => ${ret};
`;
}

/** ② The machine-owned conformance shim at `src/lib/<name>.ts`. */
export function buildExternFunctionShim(fn: UiFunctionIR): string {
  const rel = fn.externPath.replace(/^\.?\//, "");
  return `// AUTO-GENERATED shim.  Loom owns this + './extern/${fn.name}.signature';
// you own '../${rel}' (declared via \`function ${fn.name}(...) extern from "${fn.externPath}"\`).
import { ${fn.name} as _impl } from "../${rel}";
import type { ${upperFirst(fn.name)}Fn } from "./extern/${fn.name}.signature";

// Compile-time conformance: the hand-written function must match the
// Loom-derived signature, or tsc fails here — the fail-fast.
export const ${fn.name}: ${upperFirst(fn.name)}Fn = _impl;
`;
}
