import { lines } from "../../util/code-builder.js";

// ---------------------------------------------------------------------------
// The authenticated HTTP surface a generated Flutter app's api calls go through
// — M-T4.12 item (1), under **D-FLUTTER-BEARER**.
//
// Before this, every Flutter api call was a BARE top-level `http.get` /
// `http.post` with no client at all: no `withCredentials` on the web, no cookie
// jar and no bearer on native.  So a `platform: flutter` deployable against an
// `auth: required` backend was 401 on literally every request — including
// `/auth/me`, which `AuthGate` reads, so the app sat on the sign-in view
// forever.  It also meant the realtime stream had no credential path to
// INHERIT (RULE 2 of the realtime contract), which is why D-FLUTTER-BEARER
// orders the client first and the stream second.
//
// TWO credentials, one per surface, because the web build and the native build
// genuinely differ:
//
//   web     `BrowserClient()..withCredentials = true` — the HttpOnly `session`
//           cookie the `/auth/callback` handshake issues, exactly what the
//           other five frontends send.
//   native  `Authorization: Bearer <token>` — an HttpOnly cookie CANNOT exist
//           on Android/iOS, and RULE 2's own reasoning ("the SPA never sees the
//           raw token") does not hold for a native app whose OIDC client
//           necessarily holds one.  Server-side this costs nothing: bearer is
//           the credential all five backends have always accepted.
//
// HOW THE CALL SITES STAY UNTOUCHED.  `lib/api_client.dart` is a DROP-IN for
// `package:http/http.dart`: it re-exports everything except the top-level
// request functions and redefines those over one shared credentialed `Client`.
// So a credentialed app swaps ONE import line per file
// (`import 'api_client.dart' as http;`) and every `http.get(apiUri(…))` in the
// reads, the forms, the auth probe, the action buttons and the async effects is
// credentialed at once — rather than eleven call sites each having to remember.
// An `auth: none` app keeps `import 'package:http/http.dart' as http;` and is
// byte-identical.
// ---------------------------------------------------------------------------

/** The `http` import a generated Flutter library emits.
 *
 *  @param credentialed  the deployable is `auth: ui` against an `auth:
 *    required` target with a declared `user { }` — the SAME predicate
 *    `realtimeStreamCredential` applies, so the stream and the ordinary calls
 *    cannot disagree about whether the app authenticates.
 *  @param prefix  `""` for a library directly under `lib/`, `"../"` for one
 *    under `lib/pages/`. */
export function flutterHttpImport(credentialed: boolean, prefix: "" | "../" = ""): string {
  return credentialed
    ? `import '${prefix}api_client.dart' as http;`
    : "import 'package:http/http.dart' as http;";
}

/** `lib/loom_bearer.dart` — the native bearer store.
 *
 *  Platform-NEUTRAL on purpose (it compiles on the web too, where it is simply
 *  never read): the app sets the token from wherever its OIDC client keeps it,
 *  and a `kIsWeb` guard at that call site would be the app's business, not
 *  Loom's.  Loom emits no OIDC client for Flutter — sign-in is a redirect to
 *  the backend's own handshake — so the token's SOURCE is the app's, which is
 *  what D-FLUTTER-BEARER says ("a bearer store fed by the app's OIDC client"). */
export const FLUTTER_BEARER_STORE_DART = `${lines(
  "// The bearer credential the NATIVE build sends (D-FLUTTER-BEARER).  An",
  "// HttpOnly cookie cannot exist on Android/iOS, so the native surface carries",
  "// an `Authorization: Bearer <token>` instead; the web build ignores this",
  "// store entirely and sends the session cookie.",
  "//",
  "// Loom emits no OIDC client for Flutter (sign-in is a redirect to the",
  "// backend's own handshake), so the token is YOURS to supply: call",
  "// `setLoomBearerToken` when your OIDC client acquires one, and",
  "// `setLoomBearerToken(null)` on sign-out.  Until you do, native requests go",
  "// out unauthenticated — which is the honest behaviour, not a silent success.",
  "// Generated by the Loom Flutter target; do not edit.",
  "",
  "/// The access token the native http client attaches to every request.",
  "String? loomBearerToken;",
  "",
  "/// Set (or clear, with `null`) the native bearer credential.",
  "void setLoomBearerToken(String? token) {",
  "  loomBearerToken = token;",
  "}",
)}\n`;

/** `lib/api_client_web.dart` — the browser half of the conditional import. */
export const FLUTTER_API_CLIENT_WEB_DART = `${lines(
  "// Web half of the api client (D-FLUTTER-BEARER): the browser's own XHR",
  "// client with credentials enabled, so the HttpOnly `session` cookie the",
  "// `/auth/callback` handshake issued rides every request — the same credential",
  "// the react / vue / svelte / angular / feliz api clients send via",
  '// `credentials: "include"`.  Generated by the Loom Flutter target; do not edit.',
  "",
  "import 'package:http/browser_client.dart';",
  "import 'package:http/http.dart' as http;",
  "",
  "http.Client loomApiClient() => BrowserClient()..withCredentials = true;",
)}\n`;

/** `lib/api_client_io.dart` — the native half of the conditional import. */
export const FLUTTER_API_CLIENT_IO_DART = `${lines(
  "// Native half of the api client (D-FLUTTER-BEARER): an `Authorization:",
  "// Bearer` injected from `loom_bearer.dart`.  A BaseClient wrapper rather than",
  "// per-call headers, so every request the app makes — reads, forms, action",
  "// buttons, the `/auth/me` probe — is credentialed without a call site having",
  "// to remember.  Generated by the Loom Flutter target; do not edit.",
  "",
  "import 'package:http/http.dart' as http;",
  "",
  "import 'loom_bearer.dart';",
  "",
  "class _LoomBearerClient extends http.BaseClient {",
  "  final http.Client _inner = http.Client();",
  "",
  "  @override",
  "  Future<http.StreamedResponse> send(http.BaseRequest request) {",
  "    final token = loomBearerToken;",
  "    if (token != null && token.isNotEmpty) {",
  "      request.headers['Authorization'] = 'Bearer $token';",
  "    }",
  "    return _inner.send(request);",
  "  }",
  "",
  "  @override",
  "  void close() {",
  "    _inner.close();",
  "    super.close();",
  "  }",
  "}",
  "",
  "http.Client loomApiClient() => _LoomBearerClient();",
)}\n`;

/** `lib/api_client.dart` — the drop-in façade every credentialed library
 *  imports `as http`. */
export const FLUTTER_API_CLIENT_DART = `${lines(
  "// The authenticated HTTP surface (D-FLUTTER-BEARER).  A DROP-IN for",
  "// `package:http/http.dart`: it re-exports everything except the top-level",
  "// request functions and redefines those over one shared credentialed",
  "// `Client`, so a call site stays `http.get(apiUri(…))` and the credential is",
  "// decided in exactly one place.",
  "//",
  "//   web     BrowserClient()..withCredentials = true  (the session cookie)",
  "//   native  Authorization: Bearer <loomBearerToken>  (a cookie cannot exist)",
  "//",
  "// Generated by the Loom Flutter target; do not edit.",
  "",
  "import 'dart:convert';",
  "",
  "import 'package:http/http.dart' as http;",
  "",
  "import 'api_client_io.dart' if (dart.library.js_interop) 'api_client_web.dart';",
  "",
  "export 'package:http/http.dart'",
  "    hide get, post, put, patch, delete, head, read, readBytes;",
  "export 'loom_bearer.dart';",
  "",
  "/// The one credentialed client every generated api call shares.",
  "final http.Client loomHttp = loomApiClient();",
  "",
  "Future<http.Response> get(Uri url, {Map<String, String>? headers}) =>",
  "    loomHttp.get(url, headers: headers);",
  "",
  "Future<http.Response> post(Uri url,",
  "        {Map<String, String>? headers, Object? body, Encoding? encoding}) =>",
  "    loomHttp.post(url, headers: headers, body: body, encoding: encoding);",
  "",
  "Future<http.Response> put(Uri url,",
  "        {Map<String, String>? headers, Object? body, Encoding? encoding}) =>",
  "    loomHttp.put(url, headers: headers, body: body, encoding: encoding);",
  "",
  "Future<http.Response> patch(Uri url,",
  "        {Map<String, String>? headers, Object? body, Encoding? encoding}) =>",
  "    loomHttp.patch(url, headers: headers, body: body, encoding: encoding);",
  "",
  "Future<http.Response> delete(Uri url,",
  "        {Map<String, String>? headers, Object? body, Encoding? encoding}) =>",
  "    loomHttp.delete(url, headers: headers, body: body, encoding: encoding);",
  "",
  "Future<http.Response> head(Uri url, {Map<String, String>? headers}) =>",
  "    loomHttp.head(url, headers: headers);",
  "",
  "Future<String> read(Uri url, {Map<String, String>? headers}) =>",
  "    loomHttp.read(url, headers: headers);",
)}\n`;
