// `lib/ref_label.dart` — the Flutter twin of the React per-cell reference label
// (`react/ref-label-runtime.ts` carries the rationale).  A `ConsumerWidget`
// over an `autoDispose.family` keyed by the record's URL: Riverpod shares one
// request per distinct record across every row that watches it, and drops the
// entry once no row does, so a later visit re-reads a renamed record.
// `fallback` (the id text) renders while loading, on error, and when the record
// has no non-empty `display`.

import { lines } from "../../util/code-builder.js";
import { flutterHttpImport } from "./api-client.js";

export const FLUTTER_REF_LABEL_PATH = "lib/ref_label.dart";

/** The call-site marker a rendered page carries when it needs the widget. */
export const FLUTTER_REF_LABEL_MARKER = "LoomRefLabel(";

export function renderFlutterRefLabel(credentialed: boolean): string {
  return lines(
    "// Labels a cross-aggregate reference with the referenced record's",
    "// `display`. Generated by the Loom Flutter target; do not edit.",
    "",
    "import 'dart:convert';",
    "",
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    flutterHttpImport(credentialed),
    "",
    "import 'config.dart';",
    "",
    "final loomRefLabelProvider = FutureProvider.autoDispose.family<String?, String>((ref, path) async {",
    "  final res = await http.get(apiUri(path));",
    "  if (res.statusCode != 200) return null;",
    "  final body = jsonDecode(res.body);",
    "  final display = body is Map<String, dynamic> ? body['display'] : null;",
    "  return display is String && display.isNotEmpty ? display : null;",
    "});",
    "",
    "class LoomRefLabel extends ConsumerWidget {",
    "  const LoomRefLabel({super.key, required this.path, required this.fallback});",
    "",
    "  final String path;",
    "  final Widget fallback;",
    "",
    "  @override",
    "  Widget build(BuildContext context, WidgetRef ref) {",
    "    final label = ref.watch(loomRefLabelProvider(path)).valueOrNull;",
    "    return label == null ? fallback : Text(label);",
    "  }",
    "}",
  );
}
