// Typed fixture builders for the Loom IR unions (M-T9.50).
//
// Two thirds of the `test/` typecheck debt was one shape: a test builds a
// partial IR node and hands it to a consumer typed on the FULL union.  The two
// failure modes both come from annotating a builder with the union itself:
//
//   const thisProp = (n: string): ExprIR => ({ kind: "ref", name: n, refKind: "this-prop" });
//   renderTsExpr({ kind: "unary", op: "-", operand: { ...thisProp("total"), type: MONEY } });
//
//   - spreading a union-typed value and adding a field produces a union of
//     every variant + that field, and excess-property checking rejects it for
//     the variants that do not declare it (TS2322/TS2353); and
//   - a literal that omits a REQUIRED field of its variant (`match` without
//     `variantArms`) is only caught once the annotation names the variant.
//
// The fix is to name the VARIANT, not the union.  `ExprOf<"ref">` is the `ref`
// arm with its own optional `type`, so the spread above type-checks and still
// flows into an `ExprIR` parameter.  Builders here return variant types for the
// same reason; nothing widens to the union.
//
// These are type-level only — every builder returns exactly the object literal
// the hand-written fixture used to spell, so swapping one in cannot move a
// generated byte.

import type {
  DeployableIR,
  ExprIR,
  LiteralKind,
  PrimitiveName,
  RefKind,
  StmtIR,
  SystemIR,
  TypeIR,
  WorkflowStmtIR,
} from "../../src/ir/types/loom-ir.js";

// ---------------------------------------------------------------------------
// Variant narrowing — the piece most call sites actually need.
// ---------------------------------------------------------------------------

/** The `ExprIR` arm whose discriminator is `K` (e.g. `ExprOf<"ref">`). */
export type ExprOf<K extends ExprIR["kind"]> = Extract<ExprIR, { kind: K }>;
/** The `StmtIR` arm whose discriminator is `K`. */
export type StmtOf<K extends StmtIR["kind"]> = Extract<StmtIR, { kind: K }>;
/** The `TypeIR` arm whose discriminator is `K`. */
export type TypeOf<K extends TypeIR["kind"]> = Extract<TypeIR, { kind: K }>;
/** The `WorkflowStmtIR` arm whose discriminator is `K`. */
export type WorkflowStmtOf<K extends WorkflowStmtIR["kind"]> = Extract<WorkflowStmtIR, { kind: K }>;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** `{ kind: "primitive", name }` — the scalar type node. */
export const primType = (name: PrimitiveName): TypeOf<"primitive"> => ({ kind: "primitive", name });

/** `{ kind: "array", element }`. */
export const arrayType = (element: TypeIR): TypeOf<"array"> => ({ kind: "array", element });

export const STRING_T: TypeOf<"primitive"> = primType("string");
export const INT_T: TypeOf<"primitive"> = primType("int");
export const DECIMAL_T: TypeOf<"primitive"> = primType("decimal");
export const MONEY_T: TypeOf<"primitive"> = primType("money");
export const BOOL_T: TypeOf<"primitive"> = primType("bool");

// ---------------------------------------------------------------------------
// Expressions
// ---------------------------------------------------------------------------

/** `{ kind: "literal", lit, value }`. */
export const litExpr = (lit: LiteralKind, value: string): ExprOf<"literal"> => ({
  kind: "literal",
  lit,
  value,
});

/** `{ kind: "ref", name, refKind }`, with the optional resolved `type`. */
export const refExpr = (name: string, refKind: RefKind, type?: TypeIR): ExprOf<"ref"> =>
  type === undefined ? { kind: "ref", name, refKind } : { kind: "ref", name, refKind, type };

/** A `refKind: "param"` reference. */
export const paramRef = (name: string, type?: TypeIR): ExprOf<"ref"> =>
  refExpr(name, "param", type);

/** A `refKind: "this-prop"` reference — a field read inside an aggregate. */
export const thisPropRef = (name: string, type?: TypeIR): ExprOf<"ref"> =>
  refExpr(name, "this-prop", type);

/** `{ kind: "member", … }` — a typed member read. */
export const memberExpr = (
  receiver: ExprIR,
  member: string,
  receiverType: TypeIR,
  memberType: TypeIR,
): ExprOf<"member"> => ({ kind: "member", receiver, member, receiverType, memberType });

/** The boolean (predicate-arms) form of `match`.
 *
 *  `variantArms` is REQUIRED on the node and empty for this form; a fixture
 *  that left it off was building a value no lowering pass produces. */
export const matchExpr = (arms: ExprOf<"match">["arms"], otherwise?: ExprIR): ExprOf<"match"> => ({
  kind: "match",
  arms,
  variantArms: [],
  ...(otherwise ? { otherwise } : {}),
});

// ---------------------------------------------------------------------------
// Structural IR — the shapes a unit test hand-builds instead of parsing a
// `.ddd`.  These return the FULL interface with empty defaults, so a caller
// overrides only what its case is about and a new required field lands here
// once rather than as a fresh `as SystemIR` in every suite.
// ---------------------------------------------------------------------------

/** A minimal `DeployableIR` — name/platform/port, everything else empty. */
export const deployableIR = (over: Partial<DeployableIR> = {}): DeployableIR => ({
  name: "api",
  platform: "node",
  platformRef: "hono@v5",
  contextNames: [],
  dataSourceNames: [],
  channelSourceNames: [],
  hostedUiNames: [],
  serves: [],
  uiBindings: [],
  port: 3000,
  ...over,
});

/** A minimal `SystemIR` — a name and empty collections. */
export const systemIR = (over: Partial<SystemIR> = {}): SystemIR => ({
  name: "Sys",
  subdomains: [],
  deployables: [],
  e2eTests: [],
  uis: [],
  apis: [],
  storages: [],
  dataSources: [],
  channelSources: [],
  timerSources: [],
  layouts: [],
  ...over,
});
