// Make the live-mission counts CODE, not prose (experience_gathered.md §91:
// "a count in prose is a cache with no invalidation story").
//
// `docs/new-plan/README.md` used to carry a hand-typed sentence — "175 headings
// in all, 2026-09-10 count; the per-track table above is the 09-06 count and
// T6/T8/T9 have grown since" — which is the trap in one line: it was accurate
// when written, it named its own staleness, and nobody could tell WHICH of the
// two numbers to believe. Both the per-track table and the total are now
// generated from the track files themselves.
//
// The source of truth is the headings: every `## M-Tx.y — <title> — <status> ·
// …` line under `docs/new-plan/T*.md` (live) and `docs/new-plan/archive/
// T<n>-done.md` (archived). A mission's status is the first backtick-quoted
// span in the last ` — `-separated segment of its heading — the segment that
// carries `open` / `partial` / `blocked(X)` / … before the size and priority.
//
// Usage:
//   node scripts/mission-counts.mjs            print the counts as a table
//   node scripts/mission-counts.mjs --json     the same as JSON
//   node scripts/mission-counts.mjs --check    exit 1 if README.md's generated
//                                              region is out of date
//   node scripts/mission-counts.mjs --write    rewrite that region in place
//
// `--check` runs in CI (test/system/mission-counts.test.ts), so archiving a
// mission or flipping a status without regenerating fails the gate instead of
// shipping a stale count.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
export const PLAN_DIR = path.join(ROOT, "docs/new-plan");
export const README_MD = path.join(PLAN_DIR, "README.md");

export const BEGIN = "<!-- mission-counts:begin (generated by scripts/mission-counts.mjs) -->";
export const END = "<!-- mission-counts:end -->";

/** The status legend from README.md §"Status legend". `blocked(X)` is
 *  normalised to `blocked`; anything outside this set is reported verbatim
 *  under `nonLegend`, because an unrecognised status is a real finding (two of
 *  them — `mostly done`, `in progress` — were live when this script landed). */
export const LEGEND = [
  "open",
  "in-flight",
  "partial",
  "blocked",
  "plan",
  "deferred",
  "recurring",
  "frozen",
  "done",
];

/** Pull the status out of a `## M-Tx.y — … — `status` · **S** · P1` heading.
 *  Returns `{ raw, legend }` — `legend` is null when the status is not one the
 *  README's legend defines. */
export function parseStatus(heading) {
  // The status is a backticked span introduced by an em-dash: `… — `partial` ·`.
  // Two shapes rule out the naive readings, and both are live in the tree:
  //
  //   - "take the LAST ` — ` segment" breaks on a status whose parenthetical
  //     itself contains an em-dash (M-T1.3, M-T1.16, M-T9.26) and on M-T6.11,
  //     whose SIZE field is a bare `—`;
  //   - "take the FIRST ` — `-introduced span" breaks on a title that IS a
  //     backticked identifier (M-T2.11 — ``encryptedAtRest`` — `blocked(…)`).
  //
  // So: the first em-dash-introduced span that is a legend token, else the LAST
  // one — which is what surfaces a status outside the legend (`mostly done`,
  // `in progress`) instead of silently reporting it as absent.
  const spans = [...heading.matchAll(/ — `([^`]+)`/g)].map((m) => m[1]);
  if (spans.length === 0) return { raw: null, legend: null };
  const normalise = (s) => s.replace(/\(.*$/, "").trim().toLowerCase();
  const hit = spans.find((s) => LEGEND.includes(normalise(s)));
  if (hit) return { raw: hit, legend: normalise(hit) };
  const raw = spans[spans.length - 1];
  return { raw, legend: null };
}

/** Every `## M-Tx.y` heading in one file, with its parsed status. */
export function missionsIn(file) {
  const src = fs.readFileSync(file, "utf8");
  const out = [];
  for (const line of src.split("\n")) {
    const m = /^## (M-T\d+\.\d+)\b/.exec(line);
    if (!m) continue;
    out.push({ id: m[1], heading: line, ...parseStatus(line) });
  }
  return out;
}

const trackNumber = (base) => Number(/^T(\d+)/.exec(base)?.[1] ?? 0);

/** Count live + archived missions per track, and live missions per status. */
export function computeCounts(planDir = PLAN_DIR) {
  const liveFiles = fs
    .readdirSync(planDir)
    .filter((f) => /^T\d+[-.].*\.md$/.test(f))
    .sort((a, b) => trackNumber(a) - trackNumber(b));

  const archiveDir = path.join(planDir, "archive");
  const tracks = [];
  const byStatus = {};
  const nonLegend = [];
  const duplicates = [];
  const seen = new Map();
  let liveTotal = 0;
  let archivedTotal = 0;

  for (const f of liveFiles) {
    const n = trackNumber(f);
    const live = missionsIn(path.join(planDir, f));
    const archiveFile = path.join(archiveDir, `T${n}-done.md`);
    const archived = fs.existsSync(archiveFile) ? missionsIn(archiveFile) : [];

    for (const m of live) {
      liveTotal++;
      if (m.legend) byStatus[m.legend] = (byStatus[m.legend] ?? 0) + 1;
      else nonLegend.push({ id: m.id, status: m.raw, file: f });
      const prior = seen.get(m.id);
      if (prior) duplicates.push({ id: m.id, files: [prior, f] });
      else seen.set(m.id, f);
    }
    archivedTotal += archived.length;

    tracks.push({ track: `T${n}`, file: f, live: live.length, archived: archived.length });
  }

  return { tracks, liveTotal, archivedTotal, byStatus, nonLegend, duplicates };
}

/** The generated README region, as markdown. */
export function renderRegion(counts) {
  const { tracks, liveTotal, archivedTotal, byStatus, nonLegend } = counts;
  const order = LEGEND.filter((s) => byStatus[s]);
  const statusLine = order.map((s) => `\`${s}\` ${byStatus[s]}`).join(" · ");
  const extra = nonLegend.length
    ? ` · **${nonLegend.length} outside the legend** (${nonLegend
        .map((m) => `${m.id} \`${m.status}\``)
        .join(", ")})`
    : "";

  const rows = tracks.map((t) => `| ${t.track} | ${t.live} | ${t.archived} |`);

  return [
    BEGIN,
    "",
    `**${liveTotal} live missions** across the ten track files, and **${archivedTotal}** archived — counted by \`node scripts/mission-counts.mjs\` over the \`## M-Tx.y\` headings themselves, not typed by hand. By status: ${statusLine}${extra}.`,
    "",
    "| Track | Live | Archived |",
    "|---|---:|---:|",
    ...rows,
    `| **all** | **${liveTotal}** | **${archivedTotal}** |`,
    "",
    `A track file should carry no \`done\` heading for long (see §Status legend); regenerate this block with \`node scripts/mission-counts.mjs --write\` whenever you archive one. \`test/system/mission-counts.test.ts\` fails if it drifts.`,
    "",
    END,
  ].join("\n");
}

/** Splice the generated region into the README text. */
export function regenerateReadme(readmeText, counts) {
  const region = renderRegion(counts);
  const start = readmeText.indexOf(BEGIN);
  const end = readmeText.indexOf(END);
  if (start === -1 || end === -1) {
    throw new Error(
      `docs/new-plan/README.md is missing the mission-counts markers (${BEGIN} … ${END})`,
    );
  }
  return readmeText.slice(0, start) + region + readmeText.slice(end + END.length);
}

function main() {
  const args = process.argv.slice(2);
  const counts = computeCounts();

  if (args.includes("--json")) {
    process.stdout.write(`${JSON.stringify(counts, null, 2)}\n`);
    return;
  }

  const readme = fs.readFileSync(README_MD, "utf8");
  const regenerated = regenerateReadme(readme, counts);

  if (args.includes("--write")) {
    if (regenerated !== readme) {
      fs.writeFileSync(README_MD, regenerated);
      process.stdout.write("docs/new-plan/README.md: mission-counts region rewritten\n");
    } else {
      process.stdout.write("docs/new-plan/README.md: already up to date\n");
    }
    return;
  }

  if (args.includes("--check")) {
    if (regenerated !== readme) {
      process.stderr.write(
        "docs/new-plan/README.md's mission-counts region is STALE.\n" +
          "Run `node scripts/mission-counts.mjs --write` and commit the result.\n\n" +
          `${renderRegion(counts)}\n`,
      );
      process.exit(1);
    }
    process.stdout.write("docs/new-plan/README.md: mission-counts region is up to date\n");
    return;
  }

  process.stdout.write(`${renderRegion(counts)}\n`);
  if (counts.duplicates.length) {
    process.stderr.write(
      `\nDUPLICATE mission ids across track files: ${counts.duplicates
        .map((d) => `${d.id} (${d.files.join(", ")})`)
        .join("; ")}\n`,
    );
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
