// Domain-service emission (Python / FastAPI) — domain-services.md, v1 Shape A.
//
// Each `domainService Pricing { operation quote(...) {...} }` lowers to a
// module of bare, stateless module-level functions (snake_cased) under
// `app/domain/services/<snake(service)>.py` — NO class, no `self`:
//
//   def quote(cart: Cart, customer: Customer) -> Decimal: ...
//
// The operation bodies render through the shared Python statement /
// expression path (`renderPyStatements` / `renderPyExpr`) — parameters
// resolve as bare locals (refKind `param`), there is no `this`.  An
// `or`-union return reuses the EXACT exception-less union shape the
// aggregate operations emit (`renderPyOperationReturnType` → `dict[str,
// object]`, with `return` tagged-dict variants from render-stmt.ts) — no
// new union machinery.
//
// CALL-SITE CONTRACT: `PY_TARGET.domainServiceCall` (render-expr.ts)
// renders a member call as BARE `quote(...)`, so the consuming module
// (the aggregate / workflow that calls it) imports the function by name
// — `domainServiceImportLines` builds those `from app.domain.services.…
// import …` lines from the calling body's IR (see aggregate.ts /
// workflows-builder.ts).
//
// Imports are computed from the declared signature types (params +
// returns) — Decimal / datetime / id NewTypes / VO+enum classes /
// aggregate classes — plus the expression-triggered ones (re / Decimal /
// datetime / DomainError / ForbiddenError) the body reaches, so the file
// passes `mypy --strict` with no unused imports.

import type {
  BoundedContextIR,
  DomainServiceIR,
  DomainServiceOperationIR,
  TypeIR,
} from "../../../ir/types/loom-ir.js";
import { readPortsForOperation } from "../../../ir/util/domain-service-read-ports.js";
import { lines } from "../../../util/code-builder.js";
import { snake } from "../../../util/naming.js";
import { PY_IMPORTS, pyRef } from "../../_imports/python.js";
import { renderPyType } from "../render-expr.js";
import { renderPyStatements } from "../render-stmt.js";
import { PORT_POOL_MODULE, repoPortName } from "../repository-port-builder.js";

/** One emitted file: the module path and its source. */
export interface PyDomainServiceFile {
  path: string;
  content: string;
}

/** The module path for a domain service — `app/domain/services/<snake>.py`. */
export function domainServicePath(serviceName: string): string {
  return `app/domain/services/${snake(serviceName)}.py`;
}

/** Emit one module per domain service in the context, or `[]` when the
 *  context declares none.  Each module is a flat set of module-level
 *  functions (stateless: no class, no `self`). */
export function renderPyDomainServices(ctx: BoundedContextIR): PyDomainServiceFile[] {
  return ctx.domainServices.map((svc) => ({
    path: domainServicePath(svc.name),
    content: renderService(svc, ctx),
  }));
}

function renderService(svc: DomainServiceIR, ctx: BoundedContextIR): string {
  const fns = svc.operations.map(renderOperation);
  const body = fns.join("\n\n\n");

  // --- import resolution -------------------------------------------------
  // Derived from the body (M-T9.84): types, expressions, statements and the
  // read-port annotations all write `PY` markers.  Only the aggregate classes
  // a signature names stay listed here — an `entity` type renders bare.
  //
  // Aggregate (`entity`) params/returns reference the aggregate class —
  // imported from its own module (`app.domain.<snake>`).  Only names that
  // are real aggregates/parts in this context import: a union variant is
  // an `error`-payload named type that never materialises at runtime (the
  // union return degrades to `dict[str, object]`), so it needs no import.
  const aggLike = new Set<string>([
    ...ctx.aggregates.map((a) => a.name),
    ...ctx.aggregates.flatMap((a) => a.parts.map((p) => p.name)),
  ]);
  const aggNames = new Set<string>();
  for (const op of svc.operations) {
    for (const p of op.params) collectEntityNames(p.type, aggNames);
    if (op.returnType) collectEntityNames(op.returnType, aggNames);
  }
  for (const n of [...aggNames]) if (!aggLike.has(n)) aggNames.delete(n);

  const header = lines(
    `"""${svc.name} domain service — stateless pure calculator (domain-services.md).`,
    "",
    "Auto-generated by Loom.  Pin via .loomignore to customise.",
    `"""`,
    "",
    PY_IMPORTS,
    ...[...aggNames].sort().map((n) => `from app.domain.${snake(n)} import ${n}`),
  );

  return `${header}\n\n\n${body}\n`;
}

function renderOperation(op: DomainServiceOperationIR): string {
  // Read-port parameters (domain-services.md rev. 4): a `reading`-tier
  // op takes one repository handle per repo it reads, AHEAD of the user params —
  // `accounts: AccountRepository` — exactly the handle the body's `repo-read`
  // arms render against (`await accounts.by_holder(holder)`) and the
  // orchestrating workflow supplies.  A PURE op has no ports, so its declaration
  // is unchanged (byte-identical).  Each read-port read awaits the repo method,
  // so a reading op is `async def` (the orchestrator awaits the call at its site).
  const ports = readPortsForOperation(op);
  // Read-port handles are typed against the domain-side PORT (audit S7 —
  // hexagonal), NOT the concrete infra repository: the domain layer must not
  // import from `app.db`.
  const portParams = ports.map(
    (p) => `${snake(p.repo)}: ${pyRef(PORT_POOL_MODULE, repoPortName(p.aggregate))}`,
  );
  const userParams = op.params.map((p) => `${snake(p.name)}: ${renderPyType(p.type)}`);
  const params = [...portParams, ...userParams].join(", ");
  const isReading = ports.length > 0;
  const kw = isReading ? "async def" : "def";
  const ret = op.returnType ? renderPyOperationReturnType(op.returnType) : "None";
  const body = renderPyStatements(op.body, "    ");
  return lines(
    `${kw} ${snake(op.name)}(${params}) -> ${ret}:`,
    ...(body.length > 0 ? [body] : ["    pass"]),
  );
}

/** Exception-less `or`-union returns carry the tagged dict the statement
 *  renderer emits — typed `dict[str, object]` (parity with the aggregate
 *  operation return type, `renderPyOperationReturnType` in emit/aggregate.ts). */
function renderPyOperationReturnType(t: TypeIR): string {
  if (t.kind === "union") return "dict[str, object]";
  return renderPyType(t);
}

/** Collect aggregate (`entity`) class names reachable through a TypeIR —
 *  these need a `from app.domain.<snake> import <Name>` import. */
function collectEntityNames(t: TypeIR, into: Set<string>): void {
  switch (t.kind) {
    case "entity":
      into.add(t.name);
      return;
    case "array":
      collectEntityNames(t.element, into);
      return;
    case "optional":
      collectEntityNames(t.inner, into);
      return;
    case "genericInstance":
      collectEntityNames(t.arg, into);
      return;
    // A `union` return degrades to `dict[str, object]`; its variant types
    // are never materialised, so they contribute no aggregate import.
  }
}
